version: '3.8'
services:
  miabelle:
    build: .
    ports:
      - '3000:3000'
    networks:
      - justdance
    env_file:
      - ./env/react.env
    volumes:
      - ./:/app
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  justdance:
    external: true
