version: '3.8'
services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./env/react.env
    volumes:
      - ./:/app
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
