export const GET_STREAMER_DATA = 'GET_STREAMER_DATA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';

// SONGS
export const GET_ALL_SONGS = 'GET_ALL_SONGS';
export const GET_SINGLE_SONG = 'GET_SINGLE_SONG';
export const FILTER_SONGS = 'FILTER_SONGS';
export const REQUEST_SONG = 'REQUEST_SONG';
export const ACTIVATE_SONG = 'ACTIVATE_SONG';
export const DEACTIVATE_SONG = 'DEACTIVATE_SONG';

// QUEUE / TWITCH
export const SET_TWITCH_CHAT_MESSAGE = 'SET_TWITCH_CHAT_MESSAGE';
export const OPEN_QUEUE = 'OPEN_QUEUE';
export const CLOSE_QUEUE = 'CLOSE_QUEUE';
export const LEAVE_QUEUE = 'LEAVE_QUEUE';

// TWITCH CHAT
export const SET_CHAT_CONNECTION_STATUS = 'SET_CHAT_CONNECTION_STATUS';
